version: '3.8'

services:
  db0:
    image: mysql:8.0
    container_name: sleipnir-db0
    environment:
      MYSQL_ROOT_PASSWORD: odin123
      MYSQL_DATABASE: db0
    volumes:
      - ./db-init/db0:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot", "-u root"]
      interval: 5s
      timeout: 10s
      retries: 10
  db1:
    image: mysql:8.0
    container_name: sleipnir-db1
    environment:
      MYSQL_ROOT_PASSWORD: odin123
      MYSQL_DATABASE: db1
    volumes:
      - ./db-init/db1:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot", "-u root"]
      interval: 5s
      timeout: 10s
      retries: 10